#############################################################################
# Makefile for building: BIN/DependSearcher
# Generated by qmake (3.1) (Qt 5.11.0)
# Project:  DepsSearcher.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile DepsSearcher.pro -spec linux-g++ CONFIG+=qtquickcompiler
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Isrc -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -IBUILD -isystem /usr/include/libdrm -IBUILD -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = DependSearcher1.0.0
DISTDIR = /home/lazarev_as/Документы/Projects/Qt/DepsSearcher/BUILD/DependSearcher1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = BUILD/

####### Files

SOURCES       = src/main.cpp \
		src/utilfunctionclass.cpp \
		src/gui/dependencygraphwidget.cpp \
		src/gui/mainwindow.cpp \
		src/gui/mainwindow_build.cpp \
		src/gui/mainwindow_settings.cpp \
		src/gui/mainwindow_tested_functional.cpp \
		src/gui/mainwindow_working.cpp \
		src/components/archivator.cpp \
		src/components/backupmanager.cpp \
		src/components/buildmanager.cpp \
		src/components/cleaner.cpp \
		src/components/dependencyparser.cpp \
		src/components/dependsworker.cpp \
		src/components/filesearcher.cpp \
		src/components/projectbasegenerator.cpp \
		src/components/projectdirectoryfileinterface.cpp BUILD/qrc_resources.cpp \
		BUILD/moc_utilfunctionclass.cpp \
		BUILD/moc_dependencygraphwidget.cpp \
		BUILD/moc_mainwindow.cpp \
		BUILD/moc_archivator.cpp \
		BUILD/moc_buildmanager.cpp \
		BUILD/moc_projectdirectoryfileinterface.cpp
OBJECTS       = BUILD/main.o \
		BUILD/utilfunctionclass.o \
		BUILD/dependencygraphwidget.o \
		BUILD/mainwindow.o \
		BUILD/mainwindow_build.o \
		BUILD/mainwindow_settings.o \
		BUILD/mainwindow_tested_functional.o \
		BUILD/mainwindow_working.o \
		BUILD/archivator.o \
		BUILD/backupmanager.o \
		BUILD/buildmanager.o \
		BUILD/cleaner.o \
		BUILD/dependencyparser.o \
		BUILD/dependsworker.o \
		BUILD/filesearcher.o \
		BUILD/projectbasegenerator.o \
		BUILD/projectdirectoryfileinterface.o \
		BUILD/qrc_resources.o \
		BUILD/moc_utilfunctionclass.o \
		BUILD/moc_dependencygraphwidget.o \
		BUILD/moc_mainwindow.o \
		BUILD/moc_archivator.o \
		BUILD/moc_buildmanager.o \
		BUILD/moc_projectdirectoryfileinterface.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_pdf.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		build.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qtquickcompiler.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		DepsSearcher.pro src/extendedtypes.h \
		src/projectsettings.h \
		src/utilfunctionclass.h \
		src/gui/dependencygraphwidget.h \
		src/gui/mainwindow.h \
		src/components/archivator.h \
		src/components/backupmanager.h \
		src/components/buildmanager.h \
		src/components/cleaner.h \
		src/components/dependencyparser.h \
		src/components/dependsworker.h \
		src/components/filesearcher.h \
		src/components/projectbasegenerator.h \
		src/components/projectdirectoryfileinterface.h src/main.cpp \
		src/utilfunctionclass.cpp \
		src/gui/dependencygraphwidget.cpp \
		src/gui/mainwindow.cpp \
		src/gui/mainwindow_build.cpp \
		src/gui/mainwindow_settings.cpp \
		src/gui/mainwindow_tested_functional.cpp \
		src/gui/mainwindow_working.cpp \
		src/components/archivator.cpp \
		src/components/backupmanager.cpp \
		src/components/buildmanager.cpp \
		src/components/cleaner.cpp \
		src/components/dependencyparser.cpp \
		src/components/dependsworker.cpp \
		src/components/filesearcher.cpp \
		src/components/projectbasegenerator.cpp \
		src/components/projectdirectoryfileinterface.cpp
QMAKE_TARGET  = DependSearcher
DESTDIR       = BIN/
TARGET        = BIN/DependSearcher


first: all
####### Build rules

$(TARGET): BUILD/ui_mainwindow.h $(OBJECTS)  
	@test -d BIN/ || mkdir -p BIN/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: DepsSearcher.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_pdf.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		build.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qtquickcompiler.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		DepsSearcher.pro \
		src/resources.qrc \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile DepsSearcher.pro -spec linux-g++ CONFIG+=qtquickcompiler
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_pdf.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
build.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qtquickcompiler.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
DepsSearcher.pro:
src/resources.qrc:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile DepsSearcher.pro -spec linux-g++ CONFIG+=qtquickcompiler

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents src/resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/extendedtypes.h src/projectsettings.h src/utilfunctionclass.h src/gui/dependencygraphwidget.h src/gui/mainwindow.h src/components/archivator.h src/components/backupmanager.h src/components/buildmanager.h src/components/cleaner.h src/components/dependencyparser.h src/components/dependsworker.h src/components/filesearcher.h src/components/projectbasegenerator.h src/components/projectdirectoryfileinterface.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/utilfunctionclass.cpp src/gui/dependencygraphwidget.cpp src/gui/mainwindow.cpp src/gui/mainwindow_build.cpp src/gui/mainwindow_settings.cpp src/gui/mainwindow_tested_functional.cpp src/gui/mainwindow_working.cpp src/components/archivator.cpp src/components/backupmanager.cpp src/components/buildmanager.cpp src/components/cleaner.cpp src/components/dependencyparser.cpp src/components/dependsworker.cpp src/components/filesearcher.cpp src/components/projectbasegenerator.cpp src/components/projectdirectoryfileinterface.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/gui/mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: BUILD/qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) BUILD/qrc_resources.cpp
BUILD/qrc_resources.cpp: src/resources.qrc \
		/usr/lib/qt5/bin/rcc \
		src/resourceFiles/templates_console/main.cpp \
		src/resourceFiles/templates_gui/mainwindow.h \
		src/resourceFiles/templates_gui/mainwindow.cpp \
		src/resourceFiles/templates_gui/main.cpp \
		src/resourceFiles/templates_gui/mainwindow.ui \
		src/resourceFiles/templates_gui/mainwindow.h \
		BUILD/ui_mainwindow.h \
		src/gui/mainwindow.h \
		src/components/projectdirectoryfileinterface.h \
		src/gui/dependencygraphwidget.h \
		src/utilfunctionclass.h \
		src/projectsettings.h \
		src/extendedtypes.h \
		src/components/projectbasegenerator.h \
		src/components/cleaner.h
	/usr/lib/qt5/bin/rcc -name resources src/resources.qrc -o BUILD/qrc_resources.cpp

compiler_qmlcache_make_all:
compiler_qmlcache_clean:
compiler_qmlcache_loader_make_all: qmlcache_loader.cpp
compiler_qmlcache_loader_clean:
	-$(DEL_FILE) qmlcache_loader.cpp
compiler_moc_predefs_make_all: BUILD/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) BUILD/moc_predefs.h
BUILD/moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -W -dM -E -o BUILD/moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: BUILD/moc_utilfunctionclass.cpp BUILD/moc_dependencygraphwidget.cpp BUILD/moc_mainwindow.cpp BUILD/moc_archivator.cpp BUILD/moc_buildmanager.cpp BUILD/moc_projectdirectoryfileinterface.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) BUILD/moc_utilfunctionclass.cpp BUILD/moc_dependencygraphwidget.cpp BUILD/moc_mainwindow.cpp BUILD/moc_archivator.cpp BUILD/moc_buildmanager.cpp BUILD/moc_projectdirectoryfileinterface.cpp
BUILD/moc_utilfunctionclass.cpp: src/projectsettings.h \
		src/extendedtypes.h \
		src/utilfunctionclass.h \
		BUILD/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/lazarev_as/Документы/Projects/Qt/DepsSearcher/BUILD/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/lazarev_as/Документы/Projects/Qt/DepsSearcher -I/home/lazarev_as/Документы/Projects/Qt/DepsSearcher/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/utilfunctionclass.h -o BUILD/moc_utilfunctionclass.cpp

BUILD/moc_dependencygraphwidget.cpp: src/utilfunctionclass.h \
		src/projectsettings.h \
		src/extendedtypes.h \
		src/gui/dependencygraphwidget.h \
		BUILD/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/lazarev_as/Документы/Projects/Qt/DepsSearcher/BUILD/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/lazarev_as/Документы/Projects/Qt/DepsSearcher -I/home/lazarev_as/Документы/Projects/Qt/DepsSearcher/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/gui/dependencygraphwidget.h -o BUILD/moc_dependencygraphwidget.cpp

BUILD/moc_mainwindow.cpp: src/components/projectdirectoryfileinterface.h \
		src/gui/dependencygraphwidget.h \
		src/utilfunctionclass.h \
		src/projectsettings.h \
		src/extendedtypes.h \
		src/components/projectbasegenerator.h \
		src/components/cleaner.h \
		src/gui/mainwindow.h \
		BUILD/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/lazarev_as/Документы/Projects/Qt/DepsSearcher/BUILD/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/lazarev_as/Документы/Projects/Qt/DepsSearcher -I/home/lazarev_as/Документы/Projects/Qt/DepsSearcher/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/gui/mainwindow.h -o BUILD/moc_mainwindow.cpp

BUILD/moc_archivator.cpp: src/utilfunctionclass.h \
		src/projectsettings.h \
		src/extendedtypes.h \
		src/components/archivator.h \
		BUILD/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/lazarev_as/Документы/Projects/Qt/DepsSearcher/BUILD/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/lazarev_as/Документы/Projects/Qt/DepsSearcher -I/home/lazarev_as/Документы/Projects/Qt/DepsSearcher/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/components/archivator.h -o BUILD/moc_archivator.cpp

BUILD/moc_buildmanager.cpp: src/utilfunctionclass.h \
		src/projectsettings.h \
		src/extendedtypes.h \
		src/components/buildmanager.h \
		BUILD/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/lazarev_as/Документы/Projects/Qt/DepsSearcher/BUILD/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/lazarev_as/Документы/Projects/Qt/DepsSearcher -I/home/lazarev_as/Документы/Projects/Qt/DepsSearcher/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/components/buildmanager.h -o BUILD/moc_buildmanager.cpp

BUILD/moc_projectdirectoryfileinterface.cpp: src/gui/dependencygraphwidget.h \
		src/utilfunctionclass.h \
		src/projectsettings.h \
		src/extendedtypes.h \
		src/components/projectbasegenerator.h \
		src/components/projectdirectoryfileinterface.h \
		BUILD/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/lazarev_as/Документы/Projects/Qt/DepsSearcher/BUILD/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/lazarev_as/Документы/Projects/Qt/DepsSearcher -I/home/lazarev_as/Документы/Projects/Qt/DepsSearcher/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/components/projectdirectoryfileinterface.h -o BUILD/moc_projectdirectoryfileinterface.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: BUILD/ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) BUILD/ui_mainwindow.h
BUILD/ui_mainwindow.h: src/gui/mainwindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/gui/mainwindow.ui -o BUILD/ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

BUILD/main.o: src/main.cpp src/gui/mainwindow.h \
		src/components/projectdirectoryfileinterface.h \
		src/gui/dependencygraphwidget.h \
		src/utilfunctionclass.h \
		src/projectsettings.h \
		src/extendedtypes.h \
		src/components/projectbasegenerator.h \
		src/components/cleaner.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/main.o src/main.cpp

BUILD/utilfunctionclass.o: src/utilfunctionclass.cpp src/utilfunctionclass.h \
		src/projectsettings.h \
		src/extendedtypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/utilfunctionclass.o src/utilfunctionclass.cpp

BUILD/dependencygraphwidget.o: src/gui/dependencygraphwidget.cpp src/gui/dependencygraphwidget.h \
		src/utilfunctionclass.h \
		src/projectsettings.h \
		src/extendedtypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/dependencygraphwidget.o src/gui/dependencygraphwidget.cpp

BUILD/mainwindow.o: src/gui/mainwindow.cpp src/gui/mainwindow.h \
		src/components/projectdirectoryfileinterface.h \
		src/gui/dependencygraphwidget.h \
		src/utilfunctionclass.h \
		src/projectsettings.h \
		src/extendedtypes.h \
		src/components/projectbasegenerator.h \
		src/components/cleaner.h \
		BUILD/ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/mainwindow.o src/gui/mainwindow.cpp

BUILD/mainwindow_build.o: src/gui/mainwindow_build.cpp src/gui/mainwindow.h \
		src/components/projectdirectoryfileinterface.h \
		src/gui/dependencygraphwidget.h \
		src/utilfunctionclass.h \
		src/projectsettings.h \
		src/extendedtypes.h \
		src/components/projectbasegenerator.h \
		src/components/cleaner.h \
		BUILD/ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/mainwindow_build.o src/gui/mainwindow_build.cpp

BUILD/mainwindow_settings.o: src/gui/mainwindow_settings.cpp src/gui/mainwindow.h \
		src/components/projectdirectoryfileinterface.h \
		src/gui/dependencygraphwidget.h \
		src/utilfunctionclass.h \
		src/projectsettings.h \
		src/extendedtypes.h \
		src/components/projectbasegenerator.h \
		src/components/cleaner.h \
		BUILD/ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/mainwindow_settings.o src/gui/mainwindow_settings.cpp

BUILD/mainwindow_tested_functional.o: src/gui/mainwindow_tested_functional.cpp src/gui/mainwindow.h \
		src/components/projectdirectoryfileinterface.h \
		src/gui/dependencygraphwidget.h \
		src/utilfunctionclass.h \
		src/projectsettings.h \
		src/extendedtypes.h \
		src/components/projectbasegenerator.h \
		src/components/cleaner.h \
		BUILD/ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/mainwindow_tested_functional.o src/gui/mainwindow_tested_functional.cpp

BUILD/mainwindow_working.o: src/gui/mainwindow_working.cpp src/gui/mainwindow.h \
		src/components/projectdirectoryfileinterface.h \
		src/gui/dependencygraphwidget.h \
		src/utilfunctionclass.h \
		src/projectsettings.h \
		src/extendedtypes.h \
		src/components/projectbasegenerator.h \
		src/components/cleaner.h \
		BUILD/ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/mainwindow_working.o src/gui/mainwindow_working.cpp

BUILD/archivator.o: src/components/archivator.cpp src/components/archivator.h \
		src/utilfunctionclass.h \
		src/projectsettings.h \
		src/extendedtypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/archivator.o src/components/archivator.cpp

BUILD/backupmanager.o: src/components/backupmanager.cpp src/components/backupmanager.h \
		src/projectsettings.h \
		src/extendedtypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/backupmanager.o src/components/backupmanager.cpp

BUILD/buildmanager.o: src/components/buildmanager.cpp src/components/buildmanager.h \
		src/utilfunctionclass.h \
		src/projectsettings.h \
		src/extendedtypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/buildmanager.o src/components/buildmanager.cpp

BUILD/cleaner.o: src/components/cleaner.cpp src/components/cleaner.h \
		src/utilfunctionclass.h \
		src/projectsettings.h \
		src/extendedtypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/cleaner.o src/components/cleaner.cpp

BUILD/dependencyparser.o: src/components/dependencyparser.cpp src/components/dependencyparser.h \
		src/utilfunctionclass.h \
		src/projectsettings.h \
		src/extendedtypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/dependencyparser.o src/components/dependencyparser.cpp

BUILD/dependsworker.o: src/components/dependsworker.cpp src/components/dependsworker.h \
		src/utilfunctionclass.h \
		src/projectsettings.h \
		src/extendedtypes.h \
		src/components/dependencyparser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/dependsworker.o src/components/dependsworker.cpp

BUILD/filesearcher.o: src/components/filesearcher.cpp src/components/filesearcher.h \
		src/utilfunctionclass.h \
		src/projectsettings.h \
		src/extendedtypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/filesearcher.o src/components/filesearcher.cpp

BUILD/projectbasegenerator.o: src/components/projectbasegenerator.cpp src/components/projectbasegenerator.h \
		src/utilfunctionclass.h \
		src/projectsettings.h \
		src/extendedtypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/projectbasegenerator.o src/components/projectbasegenerator.cpp

BUILD/projectdirectoryfileinterface.o: src/components/projectdirectoryfileinterface.cpp src/components/projectdirectoryfileinterface.h \
		src/gui/dependencygraphwidget.h \
		src/utilfunctionclass.h \
		src/projectsettings.h \
		src/extendedtypes.h \
		src/components/projectbasegenerator.h \
		src/components/filesearcher.h \
		src/components/backupmanager.h \
		src/components/dependsworker.h \
		src/components/dependencyparser.h \
		src/components/buildmanager.h \
		src/components/archivator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/projectdirectoryfileinterface.o src/components/projectdirectoryfileinterface.cpp

BUILD/qrc_resources.o: BUILD/qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/qrc_resources.o BUILD/qrc_resources.cpp

BUILD/moc_utilfunctionclass.o: BUILD/moc_utilfunctionclass.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/moc_utilfunctionclass.o BUILD/moc_utilfunctionclass.cpp

BUILD/moc_dependencygraphwidget.o: BUILD/moc_dependencygraphwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/moc_dependencygraphwidget.o BUILD/moc_dependencygraphwidget.cpp

BUILD/moc_mainwindow.o: BUILD/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/moc_mainwindow.o BUILD/moc_mainwindow.cpp

BUILD/moc_archivator.o: BUILD/moc_archivator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/moc_archivator.o BUILD/moc_archivator.cpp

BUILD/moc_buildmanager.o: BUILD/moc_buildmanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/moc_buildmanager.o BUILD/moc_buildmanager.cpp

BUILD/moc_projectdirectoryfileinterface.o: BUILD/moc_projectdirectoryfileinterface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/moc_projectdirectoryfileinterface.o BUILD/moc_projectdirectoryfileinterface.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

